---
name: Dispatch Echo

on:
  workflow_dispatch:
    inputs:
      value:
        description: Value to be echoed
        type: string
        required: false
        default: Hello, World!
      sleep:
        description: Duration
        type: string
        required: false
        default: '30'
      loglevel:
        description: Log Level
        type: choice
        options:
          - info
          - warning
          - error

jobs:
  echo:
    name: Echo

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Sleep
        run: sleep ${{ inputs.sleep }}

      - name: Echo
        run: 'echo "${{ inputs.loglevel }}: ${{ inputs.value }}"'
