---
name: Dispatch Echo (no inputs)

on:
  workflow_dispatch:

jobs:
  echo:
    name: Echo

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Sleep
        run: sleep 30

      - name: Echo
        run: echo 'Hello, World!'
